services:

  mysql:

    image: mysql:8.0

    container_name: agrochain-mysql

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:

      # Base de datos persistente
      - mysql_data:/var/lib/mysql

      # Scripts SQL del proyecto
      - ./sql:/scripts

      # Logs (los usaremos más adelante)
      - ./logs:/logs

volumes:

  mysql_data: